### ISSUE TITLE
More info on 2023-10-16-TeardownInexpensiveChildrenCamera?

### ISSUE THREAD

**Issue by l4sh** [saeugetier/saeugetier.github.io#1]
Hey, I just got one of these cameras to play around with. Did you have any luck in finding more information than [what you posted in your blog](https://github.com/saeugetier/saeugetier.github.io/blob/0a0826bafd547885e357651c618d92c80ed4fd6a/_posts/2023-10-16-TeardownInexpensiveChildrenCamera.md)?

Got the one with a Spreadtrum SC5631F with version string `YX_Q5_EN_0828_NV3023_A 12:11:19LCD:0x3025/0x3025`. Mine has a 400 mAh battery, other than that looks about the same as the one you posted with a different color.

I guess next step is try to see where I get to with https://github.com/ilyakurdyukov/spreadtrum_flash

**Comment by saeugetier** [comment]
I haven't done anything else than documented in the article. An idea was to swap the camera or display modules in order to see if they are interchangeable. But I dad no bigger plans, because there are enough hobby projects for now.
